%% *midpoint2D*
%% *definition*
function [imFractal] = midpoint2D(nIter,H,seed)
%% *purpose*
%  2D fractal surface generated by midpoint displacement method
%% *examples*
%{ 
    nIter = 7; % number of iterations size of image is 2^nIter+1
    seed = 19850615; % seed enables repeatability
    H = 0.5; % Hurst parameters a values between 0 and 1
    im = midpoint2D(MaxLevel,H,seed);
    N = 2.0^MaxLevel;
    figure('Color','white');
    imagesc(-N/2:N/2,-N/2:N/2,im); %,[-3 3]);
    title({'Fractional Brownian Motion';['Hurst =' num2str(H) ...
            ' Fractal Dimension =' num2str(3-H)]},'fontsize',14);
    axis equal
    axis tight
    colormap(bone);
    colorbar
    set(gca,'fontweight','bold');
%}
%% *inputs*
%  nIter - number of iterations of midpoint algorithm and determines the
%      size of the image (2^MaxLevel+1)
%  H - Hurst Parameter. The Hurst parameter is global characteristic of the
%      field.  Fractal dimension, D, is a localized parameter, but for this
%      process it is related to H via: D+H=n+1 where n is the integral
%      dimension (here a 2D array so n=2).  The fractal dimension of the
%      field is D = 3 - H.  Since D > 0, H <=3;
%  seed - random number seed for repeatable fields
%% *outputs*
%  imFractal - (N+1)x(N+1) array of double values with 2D fractional
%              brownian motion of fractal dimension, D = 3 - H
%% *references*
%  Barnsley, Devaney, Mandelbrot, Peitgen, Saupe, and
%  Voss (1988) The Science of Fractal Images, Springer-Verlag
%  See Section 2.5, pages 100-101 in particular
%% *history*
%  when     who   why
%  20190602 mnoah original code (original modified algorithm)
%% *start*
if (H < 0 || H > 1)
    error('Allowed Range of H is [0,1]');
end
if (~exist('seed','var'))
    seed = -1; % just a new random field every time
end
if (seed > 0)
    s = RandStream('mt19937ar','Seed',seed);
    RandStream.setGlobalStream(s);
end
N = 2.0^nIter;
imFractal = 100*ones(N+1,N+1);
sigma = 1;
imFractal(1,1) = sigma*randn(1);
imFractal(1,N+1) = sigma*randn(1);
imFractal(N+1,1) = sigma*randn(1);
imFractal(N+1,N+1) = sigma*randn(1);
BigD = N;
d = N/2;
delta = sigma;
for iIter = 1:nIter
    
    delta = delta*((0.5)^(0.5*H));
    for x = d+1:BigD:N-d+1
        for y = d+1:BigD:N-d+1
            northeast = imFractal(x+d,y+d);
            northwest = imFractal(x+d,y-d);
            southeast = imFractal(x-d,y+d);
            southwest = imFractal(x-d,y-d);
            tmp = [northeast northwest southeast southwest];
            imFractal(x,y) = sum(tmp)/4.0 + randn(1)*delta;
        end
    end
    
    delta = delta*((0.5)^(0.5*H));
    
    for x = d+1:BigD:N-d+1
        imFractal(x,1) = (imFractal(x+d,1)+imFractal(x-d,1)+imFractal(x,d+1))/3. + randn(1)*delta;
        imFractal(x,N+1) = (imFractal(x+d,N+1)+imFractal(x-d,N+1)+imFractal(x,N+1-d))/3. + randn(1)*delta;
        imFractal(1,x) = (imFractal(1,x+d)+imFractal(1,x-d)+imFractal(d+1,x))/3. + randn(1)*delta;
        imFractal(N+1,x) = (imFractal(N+1,x+d)+imFractal(N+1,x-d)+imFractal(N-d+1,x))/3. + randn(1)*delta;
    end
      
    for x = d+1:BigD:N-d+1
        for y = BigD+1:BigD:N-d+1
            east = imFractal(x,y+d);
            west = imFractal(x,y-d);
            north = imFractal(x+d,y);
            south = imFractal(x-d,y);
            tmp = [north south east west];
            imFractal(x,y) = sum(tmp)/4.0 + randn(1)*delta;
        end
    end
    
    for x = BigD+1:BigD:N-d+1
        for y = d+1:BigD:N-d+1
            east = imFractal(x,y+d);
            west = imFractal(x,y-d);
            north = imFractal(x+d,y);
            south = imFractal(x-d,y);
            tmp = [north south east west];
            imFractal(x,y) = sum(tmp)/4.0 + randn(1)*delta;
        end
    end
    
    BigD = BigD / 2;
    d = d / 2;
    
end
% normalize to zero mean and std=1
% imFractal = (imFractal - mean(imFractal(:)))/std(imFractal(:));
end